name: Ruta Karaoke Live Stream
on:
  workflow_dispatch:
jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - run: |
          # 1. Escanear y barajar la lista de temas
          rm -f list.txt
          for f in *.mp3; do ffprobe -v error "$f" >/dev/null 2>&1 && echo "file '$f'" >> list.txt; done
          shuf list.txt > list_final.txt
          
          # 2. Transmisión con usuario iulloa2005 (Puerto 9125)
          # Se mantiene el filtro -vn para ignorar carátulas y evitar el error Broken Pipe
          ffmpeg -re -stream_loop -1 -f concat -safe 0 -i list_final.txt \
          -vn -c:a libmp3lame -b:a 96k -ar 44100 -content_type audio/mpeg \
          -ice_name "Ruta Karaoke" \
          -f mp3 "icecast://iulloa2005:ruta2026@radio.nitro-server.uk:9125/"
